version: "2.4"
networks:
  # This special network is configured so that the local metadata
  # service can bind to the specific IP address that ECS uses
  # in production
  cluster_local:
    driver: bridge
    ipam:
      config:
        - subnet: "169.254.100.0/24"
          gateway: 169.254.100.1

services:
  postgres:
    networks:
      cluster_local:
        ipv4_address: "169.254.100.253"

  postgres-keycloak:
    networks:
      cluster_local:
        ipv4_address: "169.254.100.252"

  postgres-processing:
    networks:
      cluster_local:
        ipv4_address: "169.254.100.251"

  servicelocator:
    depends_on:
      - postgres
      - keycloak
    networks:
      cluster_local:
        ipv4_address: "169.254.100.2"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      SL_AUTHENTICATOR_URL: "http://keycloak"
      SL_AUTHENTICATOR_NAME: "Authenticator"
      SL_AUTHORIZATION_URL: "http://authorization"
      SL_AUTHORIZATION_NAME: "Authorization"
      SL_AUTHORIZATION_AUTHREQ: "true"
      SL_FARMS_URL: "http://farms"
      SL_FARMS_NAME: "Farms"
      SL_FARMS_AUTHREQ: "true"
      SL_ANIMALS_URL: "http://animals"
      SL_ANIMALS_NAME: "Authorization"
      SL_ANIMALS_AUTHREQ: "true"
  
  keycloak:
    depends_on: 
      - postgres-keycloak
    networks:
      cluster_local:
        ipv4_address: "169.254.100.3"

  authorization:
    depends_on:
      - postgres
      - servicelocator
      - keycloak
    networks:
      cluster_local:
        ipv4_address: "169.254.100.4"

  farms:
    depends_on:
      - postgres
      - servicelocator
      - keycloak
      - authorization
    networks:
      cluster_local:
        ipv4_address: "169.254.100.5"

  animals:
    depends_on:
      - postgres
      - servicelocator
      - keycloak
      - authorization
      - farms
    networks:
      cluster_local:
        ipv4_address: "169.254.100.6"

  processing:
    depends_on:
      - postgres-processing
      - servicelocator
      - keycloak
      - authorization
    networks:
      cluster_local:
        ipv4_address: "169.254.100.7"